insert into public.services (
  title,
  description,
  category,
  price,
  price_from,
  price_label,
  duration_minutes,
  sort_order,
  is_active,
  is_coming_soon,
  is_bookable
) values
  (
    'Knotless Braids',
    'Lightweight braids with clean parts and a natural finish.',
    'Hair',
    null,
    2500,
    'From KES 2,500',
    180,
    1,
    true,
    false,
    true
  ),
  (
    'Loc Installation',
    'Starter locs installed with palm-rolling technique.',
    'Hair',
    null,
    3500,
    'From KES 3,500',
    210,
    2,
    true,
    false,
    true
  ),
  (
    'Silk Press',
    'Smooth blowout and flat-iron finish with heat protection.',
    'Hair',
    null,
    2200,
    'From KES 2,200',
    120,
    3,
    true,
    false,
    true
  ),
  (
    'Manicure',
    'Shape, cuticle care, massage, and polish.',
    'Nails',
    null,
    1200,
    'KES 1,200',
    60,
    4,
    true,
    false,
    true
  ),
  (
    'Pedicure',
    'Soak, exfoliation, massage, and polish.',
    'Nails',
    null,
    1600,
    'KES 1,600',
    75,
    5,
    true,
    false,
    true
  ),
  (
    'Brow Shaping',
    'Precise shaping and clean-up for a defined brow.',
    'Brows',
    null,
    700,
    'KES 700',
    30,
    6,
    true,
    false,
    true
  ),
  (
    'Classic Lashes',
    'Natural-looking lash extensions for everyday wear.',
    'Lashes',
    null,
    3000,
    'KES 3,000',
    120,
    7,
    false,
    true,
    false
  ),
  (
    'Bridal Makeup',
    'Long-wear makeup with flawless finish and touch-up kit.',
    'Makeup',
    null,
    8500,
    'KES 8,500',
    150,
    8,
    false,
    true,
    false
  );
